### ISSUE TITLE
Trigger 404 view when plugin api returns 404

### ISSUE THREAD

**Issue by captbaritone** [vim-awesome/vim-awesome#104]
Related to #101 

Currently if you try to load a plugin that does not exist, you get stuck on a page that just shows the loading gif forever. We should handle the 404 response from the api and show our 404 view.

Maybe @denisinla would be interested in working on this?

![screen shot 2016-03-22 at 9 14 01 am](https://cloud.githubusercontent.com/assets/162735/13952755/a41b47cc-f00e-11e5-8e62-705f9f6e794b.png)

**Comment by denisinla** [comment]
@captbaritone I'll take a look then.

**Comment by pawel-slowik** [comment]
@captbaritone could you take a look at #366 ?
