### ISSUE TITLE
Cannot add tags to plugin

### ISSUE THREAD

**Issue by m1foley** [vim-awesome/vim-awesome#142]
Plugin URL: http://vimawesome.com/plugin/expresso-vim

I recently added this plugin to Vim Awesome. I tagged it with the `Math` tag when creating the entry. Now that it's on the site, I do not see the `Math` tag. When I try to add it back, I am unable to. [Video here](https://monosnap.com/file/PqTneVvTnpEoUADmfA9b3YA00VgMva).

**Comment by captbaritone** [comment]
Thanks very much for the report. I'll look into it tomorrow or Wednesday depending on my availability.

**Comment by captbaritone** [comment]
@m1foley Could you try again?

**Comment by m1foley** [comment]
Verified that it works.
