### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by captbaritone** [vim-awesome/vim-awesome#146]
It would be wise to have some tests that test the API from request through to response. To do that we need to setup rethinkdb in Travis.

Cc @thejsj

**Comment by thejsj** [comment]
I agree this is probably the way to go (at least for now). I've done that before and it's not too hard to do. We could use [RethinkDB Lite](https://github.com/neumino/reqlite) if we wanted to, but since we're running Python it might not make as much sense.

**Comment by captbaritone** [comment]
Yeah, let's just jump in with both feet and run a real DB instance for tests.

Blog post about setting up RethinkDB in Travis: http://blog.hiphipjorge.com/setting-up-travis-yml-tests-with-rethinkdb/ (via @thejsj)
