### ISSUE TITLE
Report broken plugins

### ISSUE THREAD

**Issue by denilsonsa** [vim-awesome/vim-awesome#170]
There is a page to submit new plugins.

There should be a page/link/button/UI to report broken plugins.

In this case, I found this: http://vimawesome.com/plugin/unicode-haskell but [the GitHub repository linked by it](https://github.com/frerich/unicode-haskell) is not found.

**Comment by captbaritone** [comment]
Interesting. In this particular case, we could probably be checking our data for plugins where the github link is dead.

Does that sound like a reasonable solution?

**Comment by denilsonsa** [comment]
Yes, sounds like a good solution.

But that made me think…

What if someone finds out a plugin is malicious? Or what if a plugin was not updated in years and is now broken? What if a plugin is broken in only some versions of vim? Should this project even try to handle such cases? Maybe not. Probably not.

**Comment by captbaritone** [comment]
All good questions. I've thought about it a bit, and at this point I think we need to focus on being a repository of factual information. Unfortunately "broken" or "malicious" could end up being somewhat subjective. Subjective doesn't scale ;)

To be fair, tags and categories are subjective, but they are at least non-judgemental.

**Comment by captbaritone** [comment]
Closing in favor of #171

**Comment by denilsonsa** [comment]
Sounds fine. Thanks!
