### ISSUE TITLE
Replace links to other vim plugins on github to links on vimawesome

### ISSUE THREAD

**Issue by tbodt** [vim-awesome/vim-awesome#181]

**Comment by captbaritone** [comment]
@tbodt You're proposing we modify the links in README files so that links that would have pointed to the GitHub repository for another Vim plugin, would instead point to that plugin's vimawesome page?

**Comment by tbodt** [comment]
Exactly.

**Comment by jonafato** [comment]
This would be a really cool feature for users of the site and definitely provide a better overall experience (no leaving the site when browsing), but I would hesitate to introduce a change like this for two reasons:

1. It introduces additional technical complexity.
    - All links now need to be processed to check whether or not they point to plugins.
    - There are bound to be edge cases that the implementation breaks (e.g. a readme deep-linking to another project may be incorrectly identified as a plugin link).
2. Plugin developers may not expect this to happen and dislike their content being modified.

To address point 2, perhaps this could be opt-in for plugin developers? Would this be any different from developers linking directly to Vim Awesome in their readmes?

**Comment by captbaritone** [comment]
Yeah, it's a cool idea, thanks @tbodt for bringing it up!

However, I think it feels odd to modify the plugin author's content (@jonfato's point number 2). The way we present the README description, it feels obvious that it's being pulled directly from GitHub. I think it would be confusing for us to be modifying the content without any clear indication of what we're doing.

While it would be pretty slick, for now I think I'm 👎 for this idea.

**Comment by divad12** [comment]
Thanks for making the call @captbaritone , thanks for suggesting @tbodt
