### ISSUE TITLE
Ignore case when scraping GitHub-based plugins

### ISSUE THREAD

**Issue by divad12** [vim-awesome/vim-awesome#22]
GitHub ignores cases in repo locations, but unfortunately we don't. This means that when we discover references to GitHub repos that are the same but cased differently, we sadly treat them as different plugins.

For example:

http://vimawesome.com/plugin/asynccommand
http://vimawesome.com/plugin/asynccommand-all-too-well

The above refers to the same plugin but their GitHub repo names are `asynccommand` and `AsyncCommand` respectively.

**Comment by captbaritone** [comment]
Fixed by #80.
