### ISSUE TITLE
A way to list all plugins

### ISSUE THREAD

**Issue by AlexK-IL** [vim-awesome/vim-awesome#292]
I'd like to write a script to download all the plugins listed on the website. Is there a way I could get a list of all plugins? Or at least those that are available through public git repositories.

**Comment by captbaritone** [comment]
@AlexK-IL Sorry for the very slow response! You'd be welcome to do a one-time pass through all the plugins by sequentially calling this endpoint: `http://vimawesome.com/api/plugins?query=&page=1` it looks like there are ~765 pages of results you would need to fetch.

You could also download our database dump (see the README). If you need a more recent dump, let me know.

Again, apologies for the very slow response.
