### ISSUE TITLE
Build instructions fail on Fedora 25: no module called flask.ext.cache

### ISSUE THREAD

**Issue by fusion809** [vim-awesome/vim-awesome#294]
Hi,

I followed your build instructions and on my 64-bit Fedora 25 machine I got the error:

```bash
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on cluster addresses: 127.0.0.1, ::1
Listening on driver addresses: 127.0.0.1, ::1
Listening on http addresses: 127.0.0.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "fusion809_pc_ir7" 5696222c-6671-44f8-88ff-d1c7a57dd9c9
/usr/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "web/server.py", line 4, in <module>
    from web.cache import cache
  File "/home/fusion809/GitHub/others/vim-awesome/web/cache.py", line 3, in <module>
    from flask.ext.cache import Cache
  File "/usr/lib/python2.7/site-packages/flask/exthook.py", line 110, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.cache
Server got SIGTERM from pid 28479, uid 1000; shutting down...
warn: Problem when checking for new versions of RethinkDB: HTTP request to update.rethinkdb.com failed.
Shutting down client connections...
All client connections closed.
Shutting down storage engine... (This may take a while if you had a lot of unflushed data in the writeback cache.)
Storage engine shut down.
Makefile:6: recipe for target 'local' failed
make: *** [local] Segmentation fault (core dumped)
[1]    28478 terminated  make
```

the precise instructions I followed was:

> Install RethinkDB version 2.3.0 from http://rethinkdb.com/docs/install/. (You may have to dig into the download archives.)
>
> Install Sass and Compass, which we use to generate our CSS.
> 
> $ gem update --system
> $ gem install bundler
> $ bundle install
> Install Python dependencies.
> 
> $ pip install -r requirements.txt
> Install Node dependencies.
> 
> $ npm install -g webpack
> $ npm install
> Start a local server serving port 5001 by invoking, in the project root directory,
> 
> $ make
> Initialize the database, tables, and indices:
> 
> $ make init_db

At the stage of running `make` I got the aforementioned error. Any ideas how to resolve this error?

Thanks for your time,
Brenton

**Comment by captbaritone** [comment]
Did you see any errors/warnings when you ran `pip install -r requirements.txt`?

**Comment by fusion809** [comment]
This is so long ago that I no longer have a Fedora 25 system. So I'll close. Very efficient way of dealing with issues, merely don't reply for long enough and they'll fix themselves or people will quit using the OS. :P

**Comment by captbaritone** [comment]
Yeah, sorry about missing this one!
