### ISSUE TITLE
bash-support is failing

### ISSUE THREAD

**Issue by Fashaun** [vim-awesome/vim-awesome#347]
Hi ,

the bash-support install guide is fail when you use vim-plug

**Comment by captbaritone** [comment]
Any idea what's going wrong? Any error messages/screenshots you could share?

**Comment by captbaritone** [comment]
Closing as a dupe of #348.

**Comment by captbaritone** [comment]
This should be resolved. Could you confirm that it now works for you? http://vimawesome.com/plugin/bash-support-vim
