### ISSUE TITLE
vim-plug no longer falls back to vim-scripts repo

### ISSUE THREAD

**Issue by nfischer** [vim-awesome/vim-awesome#348]
Unlike Vundle, vim-plug [no longer](https://github.com/junegunn/vim-plug/commit/f7e6a86807a1f0be7257620a8c425e1a32f877bb) falls back to [vim-scripts](https://github.com/vim-scripts) plugins if the user leaves off the github username:

```viml
Plug 'fugitive.vim' " This shorthand format is no longer supported
Plug 'vim-scripts/fugitive.vim' " This should be ok
Plug 'tpope/vim-fugitive' " Even better to use the maintained plugin repo instead
```

Any chance we could get vim-plug instructions updated for relevant plugins? junegunn/vim-plug#632 just got filed because of incorrect instructions for installing matchit.zip.

**Comment by nfischer** [comment]
Thanks for the quick fix, @captbaritone!

**Comment by captbaritone** [comment]
Thanks for reporting it!
