### ISSUE TITLE
Add OpenSearch support for browsers search engines extensions

### ISSUE THREAD

**Issue by anchnk** [vim-awesome/vim-awesome#361]
Hi, 

One feature that could add even more awesomeness would be [OpenSearch](http://www.opensearch.org/Specifications/OpenSearch/1.1#OpenSearch_description_document) support. I've searched if that was already done but found nothing mentioning it. **One main use case would be `vim-awesome` extension installed in browsers search engines bars**. 

I am willing to work on that feature and collaborate. This issue is mainly to gather opinions and discuss about the `OpenSearch` feature especially in the context of browsers' search engines extensions.

There is an [add-on for Firefox](https://addons.mozilla.org/en-US/firefox/addon/vimawesome/?src=search) which seems to be unofficial. 

Looking forward to read your opinion about it.

**Comment by captbaritone** [comment]
Could you give a brief outline of what would would be involved here?

**Comment by anchnk** [comment]
1. [ ] Modify `web/templates/index.html` to include a link to the [OpenSearch description document](http://www.opensearch.org/Specifications/OpenSearch/1.1#OpenSearch_description_document)

Something like:

`<link rel="search" type="application/opensearchdescription+xml" href="/static/opensearch.xml" title="Vim Awesome">`

2. [ ] Create an OpenSearch description document with vim-awesome search engine's data.

Some links that can help:

- [OpenSearch Developer Guide](http://www.opensearch.org/Documentation/Developer_how_to_guide)

I have forked the project and build it locally trying to implement that feature. However I need to understand a bit more about the OpenSearch standard as well as how vim-awesome search engine works.

**Comment by anchnk** [comment]
Also here are the [source of the unofficial addon](https://addons.cdn.mozilla.net/user-media/addons/703646/vimawesome-20160520.xml?filehash=sha256%3Ab5202d9c162827e4254014fb0250b542999b1fe358eb7cbf0355e43d0f8d78b6) which only provides an OpenSearch description document. Also I don't know if you guys plan to switch to  `HTTPS` but that would be great.

**Comment by anchnk** [comment]
@captbaritone let me know if you would like to schedule something and if you are interested in integrating this in `vim-awesome` website. Unfortunately this doesn't work on `localhost` so it needs to be hosted in some domain.
