### ISSUE TITLE
What makes a plug-in awesome?

### ISSUE THREAD

**Issue by hawkins** [vim-awesome/vim-awesome#379]
Hey there, thanks so much for the sweet site. I’ve used it for nearly a year now, ever since a friend showed it to me in school one day!

I’ve been writing a simple vim plugin for markdown editing, and I would like for it to be in this list *eventually*, tho I wouldn’t be surprised if it’s not ready for prime time yet.

To that end, I was trying to find what makes a plug-in *awesome*? Are there any requirements for plugins added to the list that I could learn from and use to improve my work, or is it purely on a discretionary basis from the creators of the site?

**Comment by saulaxel** [comment]
I'm not a maintainer but a user and can tell that the ratings are purely based on statistics.

If you look on the upper right corner of the plugin, you can two numbers: The number of users (based on web scrapping, considering Vundle, Pathogen and NeoBundle managers), and the number of stars in github. 
![awesomestatistics](https://user-images.githubusercontent.com/17931304/44952383-89a2f480-ae43-11e8-9d98-e52cbbeb2fc3.png)

**Comment by vamshi9666** [comment]
i think the title of this issue is too broad. try to keep some title like " How do a plugin be featured ?" . tel me if i understood this in wrong way .

**Comment by hawkins** [comment]
Fair, would “what are the requirements for a plugin to be listed?” be clearer?

I worded it the way I did because the readme and website suggest they only list awesome plugins, and that’s ambiguous, so I asked “what makes a plug-in awesome?” 🤷‍♂️ You’re totally right tho, it’s too broad as is
