### ISSUE TITLE
The website is down (502 Bad Gateway)

### ISSUE THREAD

**Issue by Zebradil** [vim-awesome/vim-awesome#382]

**Comment by matrixise** [comment]
I am really sorry, but could you restart the back-end server... Thank you.

**Comment by thedracle** [comment]
I spun up a mirror on a free EC2 instance in the short term, because I can't live life without vimawesome!

http://vimawesome.jsonthomas.com/

**Comment by thedracle** [comment]
It looks like it's back up now... Maybe some automated system reset it?
