### ISSUE TITLE
Fix sidebar on short screens

### ISSUE THREAD

**Issue by divad12** [vim-awesome/vim-awesome#42]
From an email:

> The sidebar, which has position:fixed, does not allow me to access the
> items in its navigation: when any of the navigation items in the left
> sidebar expand, items in it become inaccessible to me because it goes
> past my field of view. Solution: don't make it position:fixed. Maybe
> just have the "VimAwesome" logo be position:fixed.

**Comment by mgedmin** [comment]
+1
