### ISSUE TITLE
Unclear how to add multiple tags in submit form

### ISSUE THREAD

**Issue by mgedmin** [vim-awesome/vim-awesome#58]
http://vimawesome.com/submit

![screenshot](https://cloud.githubusercontent.com/assets/159967/5643595/f174121c-9662-11e4-8158-e39fa8f9c10a.png)

I've no idea how to add both "Plugin" and "Plugin mngr" as tags.  Are tags comma-separated?  Semicolon-separated?  Surely not space-separated, since tags can have embedded spaces!

Attempts to discover the separator by trying '; ' or ',' and expecting a completion popup when I started typing were a failure: I didn't get a completion popup.

**Comment by captbaritone** [comment]
It looks like currently you have to press enter twice to select a tag. This is not very intuitive and should probably be fixed.
