### ISSUE TITLE
Behat is a PHP framework not a Vim plugin

### ISSUE THREAD

**Issue by codeinabox** [vim-awesome/vim-awesome#69]
This is incorrectly listed as a Vim plugin http://vimawesome.com/plugin/behat

**Comment by captbaritone** [comment]
I've added it to our blacklist: https://github.com/divad12/vim-awesome/commit/377995265b23a49abc169aeaf499a4fbba224124

I'll have to dig a little more to see how/if this actual makes it into our "plugins" table.
