### ISSUE TITLE
configparser errors on .gitmodules with duplicate keys

### ISSUE THREAD

**Issue by captbaritone** [vim-awesome/vim-awesome#95]
This looks like a possible lead: http://stackoverflow.com/questions/15848674/how-to-configparse-a-file-keeping-multiple-values-for-identical-keys

From our github dotfiles scraping logs:

```
scraping rykugur/dotfiles ...ERROR:root:^[[31mCould not parse the .gitmodules file of https://api.github.com/repos/rykugur/dotfiles/contents/.gitmodules?ref=master.^[[0m
Traceback (most recent call last):
  File "/home/vim/vim-awesome/tools/scrape/github.py", line 574, in _extract_pathogen_repos
    parser.read_string(unicode(contents_unicode))
  File "/usr/local/lib/python2.7/dist-packages/configparser.py", line 733, in read_string
    self.read_file(sfile, source)
  File "/usr/local/lib/python2.7/dist-packages/configparser.py", line 728, in read_file
    self._read(f, source)
  File "/usr/local/lib/python2.7/dist-packages/configparser.py", line 1102, in _read
    lineno)
DuplicateSectionError: While reading from <string> [line 19]: section u'submodule "configs/vim/bundle/vundle"' already exists
```

Here is the file in questions:

```
[submodule "powerline"]
    path = powerline
    url = git@github.com:rykugur/powerline.git
[submodule "powerline-fonts"]
    path = powerline-fonts
    url = git@github.com:rykugur/powerline-fonts.git
[submodule "configs/vim/bundle/vundle"]
    path = configs/vim/bundle/vundle
    url = git@github.com:rykugur/vundle.git
[submodule "oh-my-fish"]
    path = oh-my-fish
    url = git@github.com:rykugur/oh-my-fish.git
[submodule "devicons"]
    path = devicons
    url = git@github.com:rykugur/devicons.git
[submodule "ls--"]
    path = ls--
  url = git@github.com:rykugur/ls--.git
[submodule "configs/vim/bundle/vundle"]
    path = configs/vim/bundle/vundle
    url = git@github.com:rykugur/vundle.git
```

Note that the 3rd and last submodules are both `"configs/vim/bundle/vundle"`

**Comment by captbaritone** [comment]
It's worth noting that this error is actually being handled, but is then being thrown into our logs via `logging.exception`: https://github.com/vim-awesome/vim-awesome/blob/master/tools/scrape/github.py#L575-L576

**Comment by captbaritone** [comment]
Maybe someone with more Git knowledge could help. Is it valid to have two submodules with the same key like this? @samv or @jemiahlee?

**Comment by pawel-slowik** [comment]
Hi @captbaritone ,

it is definitely _not_ valid to have submodules with the same path: https://git-scm.com/docs/gitmodules
> All submodule paths must be unique within the .gitmodules file.

In theory, it might be valid to have submodules with identical names, but different paths. In practice, that kind of strange configuration seems to work in older Git versions (2.1.4), but not in newer (2.9.0 crashes with _fatal: no submodule mapping found in .gitmodules_).

The offending file had both duplicated names and paths, so it's definitely not a valid `.gitmodules` file.
Also, if you have a look at its history, the duplicates are obviously a mistake resulting from a bad merge, where one side removed `vim/bundle/vundle` and readded it as `configs/vim/bundle/vundle`, while the other changed `vim/bundle/vundle` to `configs/vim/bundle/vundle`:
merge: https://github.com/rykugur/dotfiles/commit/4120dbbbfa6de373f453d76c45e42b7bb56a37fb
"removed / readded" side: https://github.com/rykugur/dotfiles/commit/3fe0be56e1b2e72abcd1d5d596c993d78a6d9bd5
"changed" side: https://github.com/rykugur/dotfiles/commit/10bd694831f674fbd9408473415d814338a87f06

So in my opinion you could just close this and not worry about it.

**Comment by captbaritone** [comment]
Excellent. Thank you for the detailed response! Closing.
